### ISSUE TITLE
UPRN look up

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#132]
This is fairly large.  When we get data in URPN format, we will need to handle it in a slightly different way.

This might look something like:

1. Detect if the council supplied data as UPRNs
2. Ask the user for a house name/number
3. Figure out how to go from postcode + name/number to UPRN
4. Return the correct polling station URL.

There are a few hard to figure out problems in this issue, so we should split it into something smaller after some conversations.

**Comment by chris48s** [comment]
> Figure out how to go from postcode + name/number to UPRN

As I understand it, this is the difficult (or at least expensive) part because in order to do this, you need a licence for [OS AddressBase](https://www.ordnancesurvey.co.uk/business-and-government/products/addressbase-products.html). This is not available under an Open Government Licence, as explained here: https://www.ordnancesurvey.co.uk/about/governance/policies/addressbase-uprn.html
This is because it incorporates PAF data, which has licence fees associated with it. There's been plenty of discussion/recommendations around opening up the PAF, for example:
https://theodi.org/consultation-responses/postcode-address-file-ofcom
https://data.gov.uk/blog/open-data-user-group-response-to-rm-postcode-address-file-licensing-consultation-%E2%80%93-september-2013
https://data.gov.uk/library/the-benefits-of-an-open-national-address-dataset
but nothing has really changed and isn't likely to.

This licensing issue is also why councils are either providing addresses or UPRNs, but not both.

I think not having a licence for OS AddressBase is a showstopper on this :(

**Comment by symroe** [comment]
I think this is done?

**Comment by chris48s** [comment]
> I think this is done?

Agreed: closed by 6b69d8b
