### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#134]
We need to support more than one language

**Comment by symroe** [comment]
Coments from @chris48s: 

> Welsh is quite a painful language for i18n because it uses mutations. This means that most words have multiple different ways of spelling them depending on the context they're being used in. For example the Welsh for Cardiff (on its own) is "Caerdydd", but if you're saying "in Cardiff", the word mutates and the spelling becomes "Nghaerdydd" so "in Cardiff" is "Yng Nghaerdydd". Whereas in English you can get away with doing stuff like "Based on your postcode, you are in $city", this kind of thing often doesn't work properly in Welsh (or is more complicated) because "yn Caerdydd" doesn't make any sense. As such, there's likely to be some work to do on "refactoring" (for want of a better word) the English text (and/or string substitution logic) so that it can be translated coherently.

> That said, I note that none of your strings are marked for translation - so even though some of the English copy might need to be tweaked, I reckon that going through and marking strings for translation is a good first step. This would make it possible to produce a .po file and make this job more accessible if you do find someone able/willing to translate. Would you agree with that assessment? I'd be willing to start grinding through that if this is a high priority task.

**Comment by symroe** [comment]
Very good insight into Welsh that I would have no idea about.  I assume people have found ways to get around this problem in the past?

We have some people at NUS Wales who are willing to do the translations, so I expect we only need to provide a .po file for them (or a https://www.transifex.com/ account).

https://github.com/mysociety/yournextrepresentative has a Welsh translation, so maybe we should ask the people who did that how they found it.

As for priority – adding i18n tags might be good for new work, but I expect the codebase to change quite a lot over the next couple of months, so we might not want to do too much work up front.  I think it might be best done when we think the code is a little more stable.

**Comment by chris48s** [comment]
>  I assume people have found ways to get around this problem in the past?

Oh absolutely - this is something that is worth being aware of, rather than a showstopper.

Sometimes the path of least resistance is to compromise a little bit on the English text to make it easier to translate - so in the above example, you could change the English text to something like "Your city: $city", which is maybe a bit less 'friendly' but makes the i18n simpler.

Alternatively, you might be able to handle some cases by 'slicing' strings differently - so again in terms of the above example you might be able to do something like "Based on your postcode, you are $incity" and then sub in "in Cardiff" or "Yng Nghaerdydd" (I'm not actually certain if that is the right place to put the break in that situation, but you get the idea).

This is a process that a good translator will be able to help you with, but sometimes it can involve a bit of iteration. Also how much of an issue this will present depends on how 'dynamic' your text is. If the copy is mostly static, it may not be a big problem.

**Comment by chris48s** [comment]
Closed by 3c3026e ?

**Comment by chris48s** [comment]
Closing as we do now have Welsh version and current issues relating to updating translations are logged under #244
