### ISSUE TITLE
Find ways to reassure data providers

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#141]
> How do I as a data provider know that your representation of the data is accurate? What ‘processing’ of it do you do?
> 
> Polling district data often changes, especially close to elections. How do I as a data provider know that the data on Democracy Club’s site will be up-to-date with any changes?
> 
> Residents enter a postcode in order to find their polling station, but how accurate is this? Some postcodes can refer to more than one district.

**Comment by chris48s** [comment]
I've chewed this over a bit and here are some thoughts (quite a lot, actually). I may be raising more questions than answers at this point, but lets chuck some ideas around...

Data Quality: Garbage in - Garbage Out
--------------------------------------
The first thing that springs to mind is that the project's ability to serve up accurate/high quality data is heavily dependent on the source data quality. If councils send in data that is incomplete or of poor quality then there is a much higher risk that users might be shown inaccurate data. One thing that councils can do to minimise the potential for this is to provide high quality data in the first place.
Have you considered (at least when dealing with councils who are more engaged in the process) putting together some kind of statement that says if they provide attributes X formatted like Y in format Z (or whatever) then certain assurances about how it will be processed and the quality of resulting output can also be met? Obviously the assurances made in such an statement would have to be quite carefully considered, and probably some of the following points would need to be addressed first. Doing something like that would provide some of that reassurance, but also put some of the responsibility on the relevant councils.

UPRNs/postcodes that cross boundaries
-------------------------------------
As you've raised in issue #123, there is an issue around postcodes that cross boundaries. This is probably a sufficiently common occurrence to represent a non-trivial problem when dealing with very granular boundaries like this. I deliberately haven't commented on this issue because I've not really got as far as digging into any data provided like this and seeing what it looks like, but while this feature doesn't exist it is going to be impossible to say that everybody is definitely going to be assigned to the right polling station unless the districts exactly match postcodes (which they probably won't).
Are there any examples of this in /data yet?
In situations where councils have only provided boundary and station data, another way to address this problem would be to add the ability to "blacklist" postcodes that are known to cross boundaries by adding a table of postcodes which is queried first before doing a 'contains' query. If the postcode is in the table, direct the user to the "we don't know where you should vote - call your council" page. Otherwise, run the 'contains' query as usual. That would provide a **mechanism** to deal with it. The difficult bit is how to find out about these postcodes so that they can be added. There may be some councils that will be able to provide that info, but I would imagine most won't. Do you have any feel for whether any councils can produce this? There is probably no point doing this if there is no way to populate it.

Geocoding
---------
One of the things that I've done in some of the import scripts I've written is try to fill in missing postcode data using geocoding. In terms of the checks I've done on this, I've basically done a basic picture check on the generated postcodes (e.g: this is an import script for Guildford - all the postcodes we've found are GU-something, RH-something or KT-something - looks sensible). Then I've spot-checked a few to see if they're on or close to the street in the address. If that seems to be broadly making things better rather than worse then I've left the api call in there. In some cases (e.g: Dundee) I've decided to remove it on that basis. What I haven't done is individually checked every single one. Obviously this is very much a "best effort" approach.
This seems like a sensible way to try and add value to data of dubious quality, but I accept that some councils might not be happy that we're effectively modifying/processing their data and possibly producing spurious results in some cases. If you think we should not be doing this, or there are particular councils who are concerned, I can remove. One way that councils can ensure this doesn't happen is to provide (complete) postcodes so we don't have to try and fill in the blanks.
Thinking about it a little more, I could add an additional check to this process:
* If geocoding returns a result, look up the postcode in mapit.
* If it isn't in the local authority we're importing data for, reject it.
* If we have additional info like a ward, it might also be possible to constrain this further in some cases.
* That doesn't ensure that it is correct but it provides another programmatic check to reject anything obviously wrong.

If you still think geocoding is useful, I will add that check to `google_geocoding_api_wrapper` and submit a PR.

Submitting Corrections
----------------------
As you've raised in issue #139 and #131, if councils (or members of the public) do spot problematic data they currently don't have a nice/streamlined way to do anything about it. Implementing this would go some way to assuring data providers that they can do something about issues (although it doesn't do anything to ensure it doesn't happen in the first place).
Have you had any further feedback on this at all?

Embedded Version
----------------
I think there is an large extent to which you can reasonably say that the project has different levels of obligation to different councils.
If a council requests an embedded version (essentially associating their name, branding and website with the project and its outputs), then there is a much higher level of expectation that data must be accurate, complete, unprocessed, etc - and this applies to both parties involved. I think this is probably where the type of agreement I suggested above under "data quality" might come into play?
If a council has responded to a FOI request by saying "here's a CSV with some incomplete address data in it and no boundaries" (or whatever), it is much more reasonable not to offer any assurances.

Test Suite
----------
As noted in #140, there aren't really any tests yet.
Saying "the project has x% code coverage" or whatever is not an argument that is going to be in any way compelling for councils, but I think that establishing a test suite will at least give you a higher level of confidence that some well-meaning but ultimately incompetent/misguided contributor (Hello :D) hasn't completely ruined your code leading to data quality problems.
Assuming you're happy with the approach in PR #149, I'll continue to add some more tests in that style.

Open Source
-----------
One of the advantages of being an open source project is that councils (any anyone else) can (in principle) inspect the code, see **exactly** what is being done with the data and propose changes. As with testing, this may not be a compelling argument for certain audiences, but I think it works in your favour that this approach offers a high level of transparency about exactly how data is being processed and what assumptions are being made about it. Data is not just going into a 'closed box'.

...and finally
--------------
Publishing misleading information doesn't benefit the project, its users or data providers and it is really important to ensure this doesn't happen. Simultaneously, the website copy is carefully worded to say "we think we know where you should vote", rather than "your council says this is 100% definitely where you should vote" (for example) so I think you've already been careful to cover off valid grounds for complaint, which helps.

**Comment by chris48s** [comment]
This is always going to be an ongoing topic, but I feel like its just Business As Usual at this point. I don't think there's anything to gain from this issue still being open in 2019.
