### ISSUE TITLE
Python 3 issues

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#144]
Fleshing out the conversation I started with @symroe on slack earlier:

- Ideally the target platform for this project should be python 3.4.
- The import scripts I've written so far are tested under python 3.4 - some of them might run in 2.7, but at least one of them definitely won't due to handling of unicode.
- I've started working on some more importers and delving a bit deeper into the base importer classes and I've started to spot some python 3 compatibility issues.

First one - steps to reproduce:
`python manage.py import_chorley`
throws
`TypeError: you have to write with a stringtype Larry...`
at
https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/polling_stations/apps/data_collection/management/commands/__init__.py#L227
under python 3.4. The import script runs fine in python 2.7.
This seems to be because the overloaded `<<` operator is expecting a str type, but `kmlfile.read()` is returning bytes (which is str in python 2, but not in python 3).

Second one - steps to reproduce:
`python manage.py import_lambeth`
throws
`AttributeError: '_csv.reader' object has no attribute 'next'`
at
https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/polling_stations/apps/data_collection/management/commands/__init__.py#L77
under python 3.4. Again, the import script runs fine in python 2.7.

It is worth noting that this exception is ultimately raised in the ffs library:
https://github.com/davidmiller/ffs/blob/master/ffs/formats.py#L90

I don't mind doing some work on this, but it would be useful to get your thoughts on how best to proceed.

**Comment by davidmiller** [comment]
ffs is my fliesystem helpers library. 

It was Python 3.x compatible when I was actively developing it, but that was before Python 3.4 and I suspect it's not been tested since er 3.2 ?

I'm partial to the API - I think it's much nicer than the Python stdlib for this kind of thing.

First error can presumably be solved by casting to a string type, the second is almost certainly the library not catering for https://www.python.org/dev/peps/pep-3114/ - the fix to which is fairly trivial.

That said, it's probably _not buying you that much in this context_, so if it's causing lots of errors I'm sure you could strip it out entirely in an hour or so :)

**Comment by chris48s** [comment]
Thanks for your feedback on this.
I tried casting to str in `import_polling_districts()` and immediately hit another compatibility issue with ffs, so I think given:

- ffs has multiple compatibility issues with python 3.4
- you've said you aren't really actively maintaining/developing it
- this project doesn't contain huge amounts of file io code

I think the easiest approach in this situation is to strip out the ffs calls and fall back to the native file io functions (even though the syntax is a little less pretty).

I've submitted a PR for this.
