### ISSUE TITLE
Check contact details of councils

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#227]
On this page... 

![image](https://cloud.githubusercontent.com/assets/8096305/14281684/7bc954d8-fb32-11e5-851d-f69185cea662.png)

...in this specific example, change to electoralservices@pembrokeshire.gov.uk.

For all other councils, let's check that we have generic-name@council.gov.uk rather than a specific individual?

**Comment by JoeMitchell** [comment]
And one from Haringey: 

Are you please able to change the number from 0208 489 2953 to 0208 489 1000?

**Comment by chris48s** [comment]
The details are scraped from registertovote.service.gov.uk. In the case of Pembs, it looks like they've updated their details on there since the scraper was last run: https://www.registertovote.service.gov.uk/register-to-vote/local-authority/W06000009
In the case of Haringey, the number on https://www.registertovote.service.gov.uk/register-to-vote/local-authority/E09000014 is still the old one they want removed.
@symroe: Do you reckon the best approach to this is manually amend the details for councils that request changes, or just get them to update with registertovote.service.gov.uk and re-run the councils scraper just before election day?

**Comment by JoeMitchell** [comment]
Ah, good to know - thanks Chris. Instinctively, I'd think we should definitely be getting councils to update the one that's closest to a central register - which seems like the gov.uk one. I'll let Haringey know.

**Comment by JoeMitchell** [comment]
Just to close up the discussion here - that service.gov.uk only updates quarterly! (so we manually changed Haringey's for them. Suspect we'll get a few more, but can close this for now!
