### ISSUE TITLE
Only report validation when all files are processed

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/UK-Polling-Stations#3051]
Democracy Counts sends two files. When uploading these, the uploader checks the smaller file first, and presents you with an ❌. Only after a further refresh does it check both files, and switch to ✔

**Comment by pmk01** [comment]
Related: sometimes the polling stations file is smaller than 1kb (especially for by-elections), which throws an error.

**Comment by symroe** [comment]
This might be tricky as I don't know how much each Lambda process knows at the time it's processing a file. We might want to deal with this in the interface, and only show the validation if we have a response for all files.

**Comment by symroe** [comment]
See #4929 for the 1kb / by-election comment above.

**Comment by chris48s** [comment]
> This might be tricky as I don't know how much each Lambda process knows at the time it's processing a file

Basically, this is why status is reported at a file level. The lambda trigger is a `s3:ObjectCreated` event, so all lambda knows is that a file just appeared. It doesn't know whether it is supposed to have a friend or not. WDIV doesn't receive the files first either - they're uploaded straight from the client to S3. This is a good thing because it means WDIV doesn't have to receive a >100Mb POST request but this is the tradeoff.

As suggested, you may be able to handle this a bit more intelligently back on WDIV when rendering the admin template. Something to the effect of (pseudo-code):

```
if EMS == "democracy counts" and file_count == 1:
   if uploaded_date < [30 seconds ago]:
       status = "⌛ waiting for second file"
    else:
       status = "❌ only one file uploaded"
```

or whatever.
