### ISSUE TITLE
Support more browsers when uploading files

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#4053]
The uploader currently uses [Promise](https://caniuse.com/promises) to deal with async token requesting and uploading. 

This is a good solution, but isn't supported by all browsers. Specifically IE11. Although IE11 is hardly used at all on the internet as a whole, I have a strong suspicion that the last 1% of users are exactly _our_ users: people in UK local authorities.

We have a couple options as to how to deal with this:

1. Just detect the browser (and no JS) and show instructions as to how to email us the data. We should do this _early_ in the process, e.g before they log in.
2. Refactor the existing JS to support IE11. There are various options here to a re-write of the code, to [using a polyfill](https://www.npmjs.com/package/promise-polyfill) (untested / used)

The initial work here is to understand the problem a little more (e.g the pre-signed upload system we're using, and why) and then to work on a solution that gives IE11 users a better experience than they have at the moment (it breaks in some ways I've not tested...maybe just hanging after pressing upload?)

**Comment by symroe** [comment]
See also:

* #2545
* #2544
* #2543
* #2542

**Comment by chris48s** [comment]
> understand the problem a little more (e.g the pre-signed upload system we're using, and why)

Just to explain this bit a little more:

- The reason it uses a pre-signed POST to S3 is so you can upload from the user's browser straight to S3. If you were to use a more "traditional" form based approach, you'd have to allow nginx to accept a >100Mb POST body in production and ensure your prod instance has the memory/disk space to accept/store that temporarily then send it on to S3. This has obvious downsides.
- The main nice thing Promise buys you over callbacks (aside from syntactic sugar) is the `Promise.all` at https://github.com/DemocracyClub/UK-Polling-Stations/blob/3c8cec245548b0060bb087dd7b9e4bec446a33ab/polling_stations/apps/file_uploads/templates/file_uploads/upload.html#L155 which gives you an easy way to kick >1 files off in parallel and then do something once _all_ of them are finished (this is more difficult to do with callbacks, although not impossible). I think this is mainly useful for Democracy Counts where you get 2 files rather than one but I don't remember off the top of my head.

---

The path of least resistance to solve this one problem is probably to polyfill it and go about your day, but other options would be:

- Explicitly rewrite this code use callbacks instead of promises

- Transpilation: Move any inline JS out to `.js` files and use a transpiler as part of your build step (when you collectstatic) to compile your JS backwards for compatibility purposes.  If all you want to do is get rid of one `Promise` here, a transpiler is overkill but more widely a transpilation step is a useful general tool because it means you can _just write modern JS_, stop caring about browser support and use all the lovely new features. Then you tell the transpiler what your browser support target is and it can port your JS back to something that will run on that browser target as a compile step. This is conceptually similar to how you write SASS in development but compile it down to CSS for the browser as a build step. You write modern javascript in development and then compile it back to old javascript as a build step. This makes the JS development game substantially easier with the tradeoff that you are now in the transpiler dependency bump maintenance game :smile:
