### ISSUE TITLE
What do we show users if they don't have an election?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#431]
> My authority [Medway] doesn’t have any scheduled elections in 2017; I wondered what message will show on the screen if anyone in Medway inputs a Medway postcode into your polling station finder?

Ideally, our EveryElection API will be able to tell us whether to display polling stations for a postcode or not. So in the above example, it would tell users that "You don't have any elections coming up."

But if that's not working to our satisfaction (i.e. it's probable we won't know about several by-elections) — what do we do?

**Comment by symroe** [comment]
"We don't know of any elections here – if you think this is wrong please _contact us_"?

**Comment by JoeMitchell** [comment]
Sounds good.

I'm thinking of a user scenario where there *is *an election that we don't
know about — they go to WDIVote on election day, they don't find it — it's
unlikely they would contact us on election day, and unlikely that we'd
respond in time.

And in a situation where we *do* have PSF data for their region, but we're
not showing it because we don't think they have an election, maybe there
should be a 'force this page to show polling stations' option? Or a 'show
previous years' option?

However, this may be so rare as to not warrant any further consideration.

**Comment by symroe** [comment]
Ah I see, I was thinking about the situation where a council official or some other state-bod checked in advance – but you're right that there's not much chance of us getting data up on the day.

It might still be worth asking if we've missed one though!

**Comment by chris48s** [comment]
I think the worst-case potential outcome would be if someone checks our site to find out where to vote because they've heard there's a local election in there area, we tell them there isn't one and so they don't vote (because they assume we're right instead of contacting to tell us we're wrong). In that situation the site is actually having the exact opposite social outcome to the desired one: we're decreasing voter participation.

The situation where potentially there was some data available but we didn't know about the elction so we didn't import it/make it available is less concerning/fairly marginal as long as we're saying "we don't know". Maybe one day when we're boasting 100% coverage or something that becomes something to be more worried about.

Maybe the right solution for this May if we're not even confident we're going to know about every election (seriously, I didn't actually realise elections were quite **this** broken!) is to just update the wording to say something to the effect of "call your council to find your polling station or check whether there is actually an election going on" (except better worded) and take a more sophisticated approach once we have better source data available.

**Comment by JoeMitchell** [comment]
Just coming back to this — several of the electoral admins I met at Tiverton don't have elections, and were keen that this message be displayed. (I guess they get quite a few people complaining about a lack of elections?! Or turning up at schools thinking that they are going to vote?!)

I suppose this also relates to WCIVF, not just polling stations. 

The EAs suggested they could email us to confirm that there are no elections in their area. One has done so (and I'm going to triple check re parish/towns) — in this case I think we could do a message like:

>According to your council, there are no elections in your area on 4 May 2017.

Then that message disappears on, say, the 11 May. Or, maybe a better generic message is:

>We're not aware of any elections in your area. If you think there may be elections in your area, please call your council to check and then let us know.* You can call your council on [number].

>[tiny text]*Why are we not certain? Because there is no canonical source of UK elections. You can help us build the free, public database at elections.democracyclub.org.uk.

**Comment by chris48s** [comment]
@JoeMitchell - I've updated PR #539 with your wording changes. In terms of knowing which areas do/don't have elections, I think that naturally sits in EveryElection so the data can be shared between WhoCanIVoteFor and WhereDoIVote.
