### ISSUE TITLE
Unused white space next to station address?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#436]
From a local gov employee: 

>One change, if we are being picky would be moving the contact info from the bottom to the space next to the polling station info. Or  maybe add your logo and relevant council’s?
 
![image](https://cloud.githubusercontent.com/assets/8096305/21816972/140c2bae-d75a-11e6-8dc7-57844a623a1e.png)

>It seems to be prime space which is currently wasted.
 
Joe: I quite like white space, but agree this might be too much. Not enough space (I think) for the contact details, but I like the idea of including the council logo...

**Comment by chris48s** [comment]
Other considerations:

1. That particular address is 5 short lines of text which makes it quite 'tall and thin', but sometimes the address we've got is only a couple of lines (depending on how nice the data we have is) or the text is much longer. For example, if the name of the building is something like  "Alderman`s Green Free Methodist Church" rather than "Portacabin"

2. You have to also consider where the content is going to 'collapse' to on mobile. Any content we put next to the polling station address (on desktop) will naturally collapse to be below the polling station and above the map on mobile. I think the map being near the top/directly under the address at mobile resolutions is important as they are more naturally 'related'. You probably don't want the layout to go

[ polling station address ]
[ council logo ]
[ map ]

for mobile users.

3. In the case where we **can't** provide a polling station, the council's phone number is in that top spot e.g: https://wheredoivote.co.uk/postcode/TF11LZ/ although maybe we should also include other contact info (e.g: the URL for the council's website, electoral services email address?) in that output. This situation is where the council contact data is most important.

**Comment by chris48s** [comment]
review after #1040
