### ISSUE TITLE
Polling Stations

### ISSUE THREAD

**Issue by jcampbell05** [DemocracyClub/UK-Polling-Stations#708]
When do you expect to have all of the polling statiosn ? I'm planning to build a chatbot using your cool API.

**Comment by chris48s** [comment]
Hi James,

The data we have access to is completely dependent on which councils publish their data or work with us by sharing their data. Some councils don't share data with us for various reasons (or sometimes share data which we are unable to use because it is incomplete) so we definitely won't achieve 100% coverage of the country.

That said, a large number of councils have sent us data this year (mainly thanks to our partnership with the Electoral Commission). Our API is currently serving up data for over a hundred council areas. I've written a bunch of new import scripts today and plan to deploy more data to the live site either tomorrow or Monday. All of the data which is currently available specifically relates to the local elections on 4 May. Our current expectation is that we will have coverage of just under 50% of areas which are having local elections by polling day on 4 May (not all areas are having local elections in May).

Once the 4 May elections have happened, we will shift our focus to data for the General Election on 8 June. In general, councils will try to maintain consistency but for various reasons venues used on 4 May might not be available for us on 8 June so the current data can't be asumed to be universally correct for the General Election.

Councils try not to make late changes to polling stations, but occasionally last minute alterations do need to be made. For example last year several polling stations were moved on polling day because of flooding. As such, we may be receiving updates or corections from councils close to or even on polling day in some cases. Our API will reflect any late changes/corrections we are notified of.

If you are using the 'finder' API endpoints (`/postcode` and `/address`), in cases where we can't provide a polling station we do provide contact details for the relevant council so you can use that to tell your users who to contact.

Best of luck with your project.
