### ISSUE TITLE
Add guidance on how to contribute polling station data

### ISSUE THREAD

**Issue by BenJam** [DemocracyClub/UK-Polling-Stations#903]
I would like to add polling station locations for BANES but I'm finding it difficult to find a process for acquiring (from my council) and or adding (from my own knowledge) polling station locations. 

Might be an idea to add something to this effect in `README.md`.

**Comment by chris48s** [comment]
Hi Ben,

In terms of Bath & North East Somerset specifically, their electoral services team have provided us with data. I wrote an import script for it yesterday and it will be live on the site later this week. I can ping you once it is deployed if you like.

More generally, our mechanism for acquiring data for this project is to contact councils and ask them to publish their data or provide it for us. We don't crowdsource data from individuals. If you want to contact a council and ask them to provide data for us, the easiest way for them to provide it is for their electoral services team to export it from their Election Management System (EMS). There are instructions at https://democracyclub.org.uk/projects/polling-stations/upload/ about how to export the data from various EMS packages.

We're currently going through the process of contacting councils (with support from the Electoral Commission) to ask for data and provide these instructions.

Cheers

**Comment by chris48s** [comment]
@BenJam - just for reference, data for Bath & North East Somerset is now live on https://wheredoivote.co.uk/

**Comment by BenJam** [comment]
Awesome thanks. I didn't realise that there wasn't a crowd sourcing effort alongside this. Again worth mentioning that as I can only assume I'm not the only person who would like this to be the de-facto standard data set on this.

**Comment by chris48s** [comment]
Yeah - usually crowdsourcing is our go-to method of acquiring a dataset. Unfortunately this particular data doesn't lend itself well to crowdsourcing.

You have to vote at your assigned polling station - you can't just go to any station. In order to ensure we are directing voters to the correct station we need more than just the polling station addresses (which could be mostly scraped from PDFs if that was all we needed). We also need either the polling district boundaries or all the registered addresses which are assigned to each polling station.

This means we either need councils to publish GIS data for their polling district boundaries and station locations, like this:
https://salforddataquay.uk/dataset/salford-polling-districts
https://salforddataquay.uk/dataset/salford-polling-stations
(there are about 40 or 50 councils who are publishing or sharing their data via APIs like this)

.. or we can take the EMS exports - this is the easiest thing for most councils to produce and share with us.

In terms of becoming the de-facto standard, we would love that too. As of today we hold data for 214 council areas in England, Wales and Scotland and it is available for re-use via our [API](https://wheredoivote.co.uk/api/). Working with the Electoral Commission is definitely helping to interest more councils in sharing data with us :)
